[package]
name = "rn_chat_panel_types"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
